### ISSUE TITLE
Add Pace as hosting sponsor

### ISSUE THREAD

**Issue by rmw** [WriteSpeakCode/writespeakcode.github.io#25]
Grab the Pace logo from [here](http://openvideoconference.org/wp-content/uploads/2011/09/Seidenberg-BlueGold.png)  

[Website link](http://www.pace.edu/seidenberg/seidenberg-programs)

Add it to data/sponsors.yml as with `sponsor_level: host`   Add host to the sponsor type hash in [config.rb](https://github.com/WriteSpeakCode/writespeakcode.github.io/blob/dev/config.rb#L47) with level: 6.

**Comment by dalrayes** [comment]
Done :)
