### ISSUE TITLE
Add OSS event sponsorship info

### ISSUE THREAD

**Issue by rmw** [WriteSpeakCode/writespeakcode.github.io#39]
Add link to sponsorship page.  https://guestlistapp.com/events/336243

Text, something like ...

>Interested in getting in front of motivated, community-focused technologists of diverse backgrounds? Just want to support diversity in tech and open source?  Sponsor this event!
> Sponsorship helps cover the cost of childcare and accessibility services, such as CART transcription and ASL interpreters.  Sponsors will have their logos on the event website, meetup page, and event slide main/break slides.  Platinum sponsors will have their name and twitter logo on all slides.

Then add that for sponsorhsip questions, they should email chicago@writespeakcode.com

**Comment by dalrayes** [comment]
We need to add Braintree logo as Silver sponsor @carolineartz 

Brand assets are here https://www.paypal-media.com/logos
